import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { Button } from "../components/ui/button";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>FundSwift</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        
        <div className="mt-8">
          <Button>Click me</Button>
        </div>

      </main>

    </div>
  );
};

export default Home;
