import Image from "next/image";
import Link from "next/link";

import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { Button } from "../components/ui/button";
import { useAccount } from "wagmi";
import { useState, useEffect } from 'react'

import WormholeBridge from '@wormhole-foundation/wormhole-connect';

import LoadFiat from '../components/LoadFiat';
import BridgeUserToken from '../components/BridgeToken';
import Container from "../components/Container";

import { Card, CardContent, CardFooter } from "../components/ui/card";

const Home: NextPage = () => {

  const { isConnected, address } = useAccount();
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Chi-Care</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>

      <Container>

        <div className="space-y-10 pb-2">
          <div className="pt-0 p-4 sm:p-6 lg:p-8 rounded-lg overflow-hidden">
            <div
              style={{ backgroundImage: `url(/img/chi-care.jpeg)` }}
              className="rounded-lg relative aspect-square md:aspect-[2.4/1] overflow-hidden bg-cover"
            >
              <div className="h-full w-full flex flex-col justify-center items-center text-center gap-y-8">
                <div className="font-bold text-3xl sm:text-5xl lg:text-6xl sm:max-w-xl max-w-xs text-black dark:text-white bg-gray-300/60 dark:bg-gray-500/60 p-4 rounded-lg">
                  <h1>Chi-Care</h1>
                  <p className="text-lg">Unveiling the future of seamless financial transfers, our application combines the brilliance of Web 3, financial oracles, and innovative tech to bring family and friends closer than ever. Bypass borders and barriers with ease, ensuring your support reaches your loved ones swiftly and accurately. Dive into a world where every transaction is more than just numbers; it's a heartfelt connection. Redefine support, cherish relationships, and embrace the new era of financial empowerment.</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="space-y-10 pb-4">
          <section id="features" className="container space-y-6 bg-slate-50 py-4 dark:bg-transparent md:py-12 lg:py-12">
            <div className="mx-auto grid justify-center gap-4 sm:grid-cols-2 md:max-w-[64rem] md:grid-cols-2">

              <div className="relative overflow-hidden rounded-lg border bg-background p-2">
                <div className="flex h-[300px] flex-col justify-between rounded-md p-6 items-center">
                  <div className="flex justify-center items-center">
                    <Image
                        src="/img/ChiCare-40.png"
                        alt="Request"
                        height={150} width={250}
                        className="img-wrapper aspect-auto object-cover rounded-lg transition-all duration-300 hover:scale-105"
                      />
                  </div>
                  <div className="space-y-2 items-center">
                    <h1 className="font-bold text-3xl">Request</h1>
                  </div>
                  <div className="space-y-2 items-center">
                    {(isClient && isConnected) && (
                      <Link href="/request">
                        <Button variant="outline" >Request Finance</Button>
                      </Link>
                    )}
                    {(isClient && !isConnected) && (
                      <ConnectButton label="Join Us"/>
                    )}
                  </div>
                </div>
              </div>

              <div className="relative overflow-hidden rounded-lg border bg-background p-2">
                <div className="flex h-[300px] flex-col justify-between rounded-md p-6 items-center">
                  <div className="flex justify-center items-center">
                    <Image
                        src="/img/ChiCare-40.png"
                        alt="Request"
                        height={150} width={250}
                        className="img-wrapper aspect-auto object-cover rounded-lg transition-all duration-300 hover:scale-105"
                      />
                  </div>
                  <div className="space-y-2 items-center">
                    <h1 className="font-bold text-3xl">Transfer</h1>
                  </div>
                  <div className="space-y-2 items-center">
                  {(isClient && isConnected) && (
                    <Link href="/transfer">
                      <Button variant="outline" >Make a Tranfer</Button>
                    </Link>
                    )}
                    {(isClient && !isConnected) && (
                      <ConnectButton label="Join Us"/>
                    )}
                  </div>
                </div>
              </div>

            </div>
            {/* <div className="mx-auto text-center md:max-w-[58rem]">
              <p className="leading-normal text-muted-foreground sm:text-lg sm:leading-7">
                Taxonomy also includes a blog and a full-featured documentation site
                built using Contentlayer and MDX.
              </p>
            </div> */}
          </section>
        </div>

        <div className="space-y-10 pb-10">
          <section id="features" className="container space-y-6 bg-slate-50 py-8 dark:bg-transparent md:py-12 lg:py-12">
            <div className="mx-auto flex max-w-[58rem] flex-col items-center space-y-4 text-center">
              <h2 className="font-heading text-3xl leading-[1.1] sm:text-3xl md:text-6xl">
              Permissionlessly help others
              </h2>
              <p className="max-w-[95%] leading-normal text-muted-foreground sm:text-lg sm:leading-7">
                Experience the future of financial empowerment with our cutting-edge application, meticulously designed to bridge borders and bring loved ones closer in an ever-evolving digital age. By integrating the advanced facets of Web 3, such as social login, account abstraction, and token bridges, coupled with the precision of financial oracles, we ensure not just swift, but also accurate monetary transfers. In a world where distances often challenge the heart's desires, our platform stands as a beacon of hope, making financial aid to family and friends not just possible, but profoundly effortless. 
              </p>
              <p className="max-w-[95%] leading-normal text-muted-foreground sm:text-lg sm:leading-7">
                Here, every transaction transcends mere numbers, becoming a warm embrace, a reassuring pat, or a celebratory high-five. We are not just changing the way you transact; we're transforming the way you connect. Dive in, and discover a realm where helping those you cherish is uncomplicated, unhindered, and unparalleled. Together, let's celebrate relationships, redefine support, and make every financial gesture a memorable one!. 
              </p>
            </div>
          </section>          
        </div>


      </Container>
      </main>

    </div>
  );
};

export default Home;
