import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { Button } from "../components/ui/button";
import { useAccount } from "wagmi";
import { useState, useEffect } from 'react'

import WormholeBridge from '@wormhole-foundation/wormhole-connect';

import LoadFiat from '../components/LoadFiat';
import BridgeUserToken from '../components/BridgeToken';


const Home: NextPage = () => {

  const { isConnected, address } = useAccount();
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>FundSwift</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <div className="my-8">
          <LoadFiat />
        </div>
        {(isClient && isConnected) && (
          <>
          <p className="text-white">Address:  {address}</p>
          <div className="my-4">
            <BridgeUserToken />
          </div>
          </>
        )}

      </main>

    </div>
  );
};

export default Home;
