
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Transfers: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Transfers</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <h1>Transfers</h1>
        
      </main>

    </div>
  );
};

export default Transfers;
